-- Schema local espelhando o projeto Montezuma (produção).
-- Gerado a partir do catálogo Postgres. Sem dados de produção.

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE SCHEMA IF NOT EXISTS private;
GRANT USAGE ON SCHEMA private TO postgres, anon, authenticated, service_role;

DO $$ BEGIN
  CREATE TYPE public.obra_modalidade AS ENUM ('empreitada', 'gestao');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE SEQUENCE IF NOT EXISTS public.cliente_mensagens_id_seq;
CREATE SEQUENCE IF NOT EXISTS public.obra_whatsapp_config_id_seq;
CREATE SEQUENCE IF NOT EXISTS public.whatsapp_messages_id_seq;

CREATE TABLE IF NOT EXISTS public."agenda" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "escritorio_id" uuid NOT NULL,
  "titulo" text NOT NULL,
  "tipo" text DEFAULT 'Outro'::text NOT NULL,
  "data_hora" timestamp with time zone NOT NULL,
  "descricao" text,
  "cliente_id" bigint,
  "status" text DEFAULT 'Agendado'::text NOT NULL,
  "criado_por" uuid,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  "grupo_recorrencia_id" uuid,
  "reserva_sala_id" uuid,
  CONSTRAINT "agenda_pkey" PRIMARY KEY (id),
  CONSTRAINT "agenda_status_check" CHECK ((status = ANY (ARRAY['Agendado'::text, 'Realizado'::text, 'Cancelado'::text]))),
  CONSTRAINT "agenda_tipo_check" CHECK (((length(btrim(tipo)) >= 1) AND (length(btrim(tipo)) <= 40))),
  CONSTRAINT "agenda_titulo_check" CHECK ((length(btrim(titulo)) > 0))
);

CREATE TABLE IF NOT EXISTS public."classes_prestadores" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "nome" text NOT NULL,
  CONSTRAINT "classes_prestadores_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."cliente_conversa_estado" (
  "telefone" text NOT NULL,
  "obra_id_selecionada" bigint,
  "atualizado_em" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "cliente_conversa_estado_pkey" PRIMARY KEY (telefone)
);

CREATE TABLE IF NOT EXISTS public."cliente_historico" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "author_id" uuid NOT NULL,
  "author_nome" text NOT NULL,
  "mensagem" text NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  "obra_id" bigint NOT NULL,
  CONSTRAINT "cliente_historico_mensagem_check" CHECK ((char_length(TRIM(BOTH FROM mensagem)) > 0)),
  CONSTRAINT "cliente_historico_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."cliente_mensagens" (
  "id" bigint DEFAULT nextval('cliente_mensagens_id_seq'::regclass) NOT NULL,
  "telefone" text NOT NULL,
  "obra_id" bigint,
  "role" text NOT NULL,
  "content" text NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "cliente_mensagens_pkey" PRIMARY KEY (id),
  CONSTRAINT "cliente_mensagens_role_check" CHECK ((role = ANY (ARRAY['user'::text, 'assistant'::text])))
);

CREATE TABLE IF NOT EXISTS public."clientes" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "nome" text,
  "tipo" text,
  "status" text,
  "pagamento" text,
  "valor_pago" double precision,
  "data" date DEFAULT now(),
  "escritorio_id" text,
  "valor_cobrado" double precision,
  "status_pmu" text,
  "protocolo_pmu" text,
  "observacao_pmu" text,
  "status_caixa" text,
  "engenheiro" text,
  "protocolo_caixa" text,
  "data_ass_caixa" date,
  "status_fin" text,
  "n_alvara" bigint,
  "n_contrato" bigint,
  "data_ass_fin" date,
  "cpf" text,
  "email" text,
  "rg" text,
  "profissao" text,
  "bairro" text,
  "rua" text,
  "numero_casa" text,
  "cidade" text,
  "estado" text,
  "cep" text,
  "complemento" text,
  "bairro_obra" text,
  "rua_obra" text,
  "numero_obra" text,
  "tamanho_m2" text,
  "lote" text,
  "quadra" text,
  "codigo_identificacao_imovel" text,
  "art" text,
  "padrao_cub" text,
  "numero_alvara" text,
  "data_expedicao" text,
  "cub_tipo_projeto" text,
  "cub_padrao" text,
  "cub_nomenclatura" text,
  "numero_processo" text,
  "obra_id" bigint,
  "foto" text,
  "escritorio" text DEFAULT 'Montezuma'::text,
  "auth_user_id" uuid,
  "telefone" text,
  CONSTRAINT "clientes_auth_user_id_key" UNIQUE (auth_user_id),
  CONSTRAINT "clientes_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."contas_pagar_fornecedor" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "material_id" bigint NOT NULL,
  "obra_id" bigint NOT NULL,
  "fornecedor_id" uuid NOT NULL,
  "descricao" text NOT NULL,
  "valor" double precision DEFAULT 0 NOT NULL,
  "data_vencimento" date,
  "status_pagamento" text DEFAULT 'Aguardando pagamento'::text NOT NULL,
  "data_pagamento" timestamp with time zone,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "contas_pagar_fornecedor_material_id_key" UNIQUE (material_id),
  CONSTRAINT "contas_pagar_fornecedor_pkey" PRIMARY KEY (id),
  CONSTRAINT "contas_pagar_fornecedor_status_pagamento_check" CHECK ((status_pagamento = ANY (ARRAY['Aguardando pagamento'::text, 'Pago'::text])))
);

CREATE TABLE IF NOT EXISTS public."cronograma_eventos" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "obra_id" bigint NOT NULL,
  "titulo" text NOT NULL,
  "descricao" text,
  "data_evento" date NOT NULL,
  "user_id" uuid DEFAULT auth.uid(),
  "created_at" timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  "cor" text DEFAULT 'blue'::text,
  "data_fim" date,
  CONSTRAINT "cronograma_eventos_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."diario_obras" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "obra_id" bigint NOT NULL,
  "user_id" uuid NOT NULL,
  "nome_usuario" text NOT NULL,
  "mensagem" text NOT NULL,
  "created_at" timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  "updated_at" timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  CONSTRAINT "diario_obras_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."entradas" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "descricao" text,
  "forma" text,
  "valor" double precision,
  "data" date,
  "escritorio_id" uuid,
  "grupo_id" text,
  "validacao" integer,
  "escritorio" text DEFAULT 'Montezuma'::text,
  CONSTRAINT "entradas_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."escritorios" (
  "id" uuid DEFAULT uuid_generate_v4() NOT NULL,
  "nome" character varying(255) NOT NULL,
  "created_at" timestamp with time zone DEFAULT now(),
  CONSTRAINT "escritorios_nome_key" UNIQUE (nome),
  CONSTRAINT "escritorios_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."etapas" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "obra_id" bigint,
  "validacao" smallint,
  "descricao" text,
  "data" date,
  CONSTRAINT "etapas_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."fornecedores" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "nome" text NOT NULL,
  "telefone" text,
  "email" text,
  "cnpj" text,
  "endereco" text,
  "nome_vendedor" text,
  "ativo" boolean DEFAULT true,
  "criado_em" timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  "foto" text,
  "escritorio" text DEFAULT 'Montezuma'::text,
  CONSTRAINT "fornecedores_cnpj_key" UNIQUE (cnpj),
  CONSTRAINT "fornecedores_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."obra_lote_itens" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "lote_id" uuid NOT NULL,
  "extrato_id" bigint NOT NULL,
  "valor" numeric DEFAULT 0 NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "obra_lote_itens_lote_extrato_unique" UNIQUE (lote_id, extrato_id),
  CONSTRAINT "obra_lote_itens_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."obra_lotes_pagamento" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "obra_id" bigint NOT NULL,
  "numero" integer NOT NULL,
  "nome" text,
  "data_criacao" date DEFAULT CURRENT_DATE NOT NULL,
  "total" numeric DEFAULT 0 NOT NULL,
  "status" text DEFAULT 'pendente'::text NOT NULL,
  "criado_por" uuid,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "obra_lotes_pagamento_obra_numero_unique" UNIQUE (obra_id, numero),
  CONSTRAINT "obra_lotes_pagamento_pkey" PRIMARY KEY (id),
  CONSTRAINT "obra_lotes_pagamento_status_check" CHECK ((status = ANY (ARRAY['pendente'::text, 'parcial'::text, 'pago'::text])))
);

CREATE TABLE IF NOT EXISTS public."obra_movimentacoes" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "obra_id" bigint NOT NULL,
  "tipo" text NOT NULL,
  "valor" numeric NOT NULL,
  "descricao" text,
  "data" date DEFAULT CURRENT_DATE NOT NULL,
  "transferencia_grupo_id" uuid,
  "obra_contra_id" bigint,
  "created_by" uuid,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "lote_pagamento_id" uuid,
  "pessoa_contra" text,
  CONSTRAINT "obra_movimentacoes_pkey" PRIMARY KEY (id),
  CONSTRAINT "obra_movimentacoes_saida_exige_lote" CHECK ((((tipo = 'saida_pagamento'::text) AND (lote_pagamento_id IS NOT NULL)) OR ((tipo <> 'saida_pagamento'::text) AND (lote_pagamento_id IS NULL)))),
  CONSTRAINT "obra_movimentacoes_tipo_check" CHECK ((tipo = ANY (ARRAY['entrada'::text, 'transferencia_entrada'::text, 'transferencia_saida'::text, 'saida_pagamento'::text]))),
  CONSTRAINT "obra_movimentacoes_transferencia_exige_grupo" CHECK ((((tipo = ANY (ARRAY['entrada'::text, 'saida_pagamento'::text])) AND (transferencia_grupo_id IS NULL) AND (obra_contra_id IS NULL) AND (pessoa_contra IS NULL)) OR ((tipo = ANY (ARRAY['transferencia_entrada'::text, 'transferencia_saida'::text])) AND (transferencia_grupo_id IS NOT NULL) AND (((obra_contra_id IS NOT NULL) AND (pessoa_contra IS NULL)) OR ((obra_contra_id IS NULL) AND (pessoa_contra IS NOT NULL) AND (length(TRIM(BOTH FROM pessoa_contra)) > 0)))))),
  CONSTRAINT "obra_movimentacoes_valor_check" CHECK ((valor > (0)::numeric))
);

CREATE TABLE IF NOT EXISTS public."obra_pedido_grupos_compra" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "pedido_id" bigint NOT NULL,
  "numero" integer DEFAULT 1 NOT NULL,
  "emitente" text NOT NULL,
  "status" text DEFAULT 'Pendente'::text NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "obra_pedido_grupos_compra_emitente_check" CHECK ((emitente = ANY (ARRAY['cliente'::text, 'montezuma'::text]))),
  CONSTRAINT "obra_pedido_grupos_compra_pedido_id_numero_key" UNIQUE (pedido_id, numero),
  CONSTRAINT "obra_pedido_grupos_compra_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."obra_pedido_itens" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "pedido_id" bigint NOT NULL,
  "material" text NOT NULL,
  "quantidade" numeric(12,2) NOT NULL,
  "data_entrega" date NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "unidade" text DEFAULT 'Un.'::text NOT NULL,
  "grupo_compra_id" bigint,
  "material_relatorio_id" bigint,
  "data_pagamento" date,
  "fornecedor_id" uuid,
  "valor" numeric(14,2),
  "etapa_nome" text,
  CONSTRAINT "obra_pedido_itens_pkey" PRIMARY KEY (id),
  CONSTRAINT "obra_pedido_itens_quantidade_check" CHECK ((quantidade > (0)::numeric))
);

CREATE TABLE IF NOT EXISTS public."obra_pedidos" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "obra_id" bigint NOT NULL,
  "status" text DEFAULT 'Pendente'::text NOT NULL,
  "solicitante_id" text,
  "solicitante_nome" text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  "numero" integer NOT NULL,
  CONSTRAINT "obra_pedidos_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."obra_whatsapp_config" (
  "id" bigint DEFAULT nextval('obra_whatsapp_config_id_seq'::regclass) NOT NULL,
  "obra_id" bigint NOT NULL,
  "recebe_atualizacoes" boolean DEFAULT true NOT NULL,
  "ultimo_resumo_enviado_em" timestamp with time zone,
  "criado_em" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "obra_whatsapp_config_obra_id_key" UNIQUE (obra_id),
  CONSTRAINT "obra_whatsapp_config_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."obras" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "cliente" text,
  "local" text,
  "status" text,
  "active" text,
  "data" date,
  "cliente_id" bigint,
  "etapas_selecionadas" jsonb DEFAULT '[]'::jsonb,
  "escritorio" text DEFAULT 'Montezuma'::text,
  "responsavel_id" uuid,
  "modalidade" obra_modalidade DEFAULT 'empreitada'::obra_modalidade NOT NULL,
  CONSTRAINT "Obras_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."orcamentos" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "nome" text,
  "valor" double precision,
  "data" date DEFAULT now(),
  "status" text,
  "escritorio_id" text,
  "escritorio" text DEFAULT 'Montezuma'::text,
  "numero_proposta" integer,
  "proposta_dados" jsonb DEFAULT '{}'::jsonb NOT NULL,
  CONSTRAINT "orcamentos_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."ordens_servico" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "numero" integer NOT NULL,
  "escritorio_id" uuid NOT NULL,
  "criador_id" uuid NOT NULL,
  "responsavel_id" uuid,
  "status" text DEFAULT 'pendente'::text NOT NULL,
  "data_emissao" date DEFAULT CURRENT_DATE NOT NULL,
  "data_conclusao" timestamp with time zone,
  "concluido_por_id" uuid,
  "responsavel_tecnico" text,
  "cliente_nome" text,
  "cliente_telefone" text,
  "cliente_email" text,
  "endereco_projeto" text,
  "objeto_servico" text,
  "escopo" jsonb DEFAULT '[]'::jsonb NOT NULL,
  "escopo_outro" jsonb DEFAULT '[]'::jsonb,
  "descricao_servicos" text,
  "data_inicio" date,
  "data_entrega_prevista" date,
  "observacoes_prazos" text,
  "valor_total" numeric,
  "formas_pagamento" jsonb DEFAULT '[]'::jsonb NOT NULL,
  "forma_pagamento_outro" jsonb DEFAULT '[]'::jsonb,
  "observacoes_gerais" text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  "responsabilidades_cliente" text,
  "endereco_rua" text,
  "endereco_numero" text,
  "endereco_bairro" text,
  "cliente_id" bigint,
  "assinatura_emissor_em" timestamp with time zone,
  "assinatura_responsavel_em" timestamp with time zone,
  CONSTRAINT "ordens_servico_escritorio_numero_unique" UNIQUE (escritorio_id, numero),
  CONSTRAINT "ordens_servico_pkey" PRIMARY KEY (id),
  CONSTRAINT "ordens_servico_status_check" CHECK ((status = ANY (ARRAY['pendente'::text, 'concluida'::text])))
);

CREATE TABLE IF NOT EXISTS public."prestadores" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "nome" text NOT NULL,
  "cnpj_cpf" text,
  "telefone" text,
  "email" text,
  "ativo" boolean DEFAULT true NOT NULL,
  "foto" text,
  "escritorio" text DEFAULT 'Montezuma'::text,
  CONSTRAINT "prestadores_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."prestadores_classes" (
  "prestador_id" bigint NOT NULL,
  "classe_id" bigint NOT NULL,
  CONSTRAINT "prestadores_classes_pkey" PRIMARY KEY (prestador_id, classe_id)
);

CREATE TABLE IF NOT EXISTS public."projecoes" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "nome" text NOT NULL,
  "cliente_nome" text,
  "contato" text,
  "endereco_obra" text,
  "descricao" text,
  "status" text DEFAULT 'Rascunho'::text NOT NULL,
  "data_proposta" date DEFAULT CURRENT_DATE NOT NULL,
  "valor_documentacao" numeric(14,2) DEFAULT 0 NOT NULL,
  "valor_projeto" numeric(14,2) DEFAULT 0 NOT NULL,
  "valor_obra" numeric(14,2) DEFAULT 0 NOT NULL,
  "itens" jsonb DEFAULT '[]'::jsonb NOT NULL,
  "observacoes" text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "projecoes_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."relatorio_extrato" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "obra_id" bigint,
  "descricao" text,
  "tipo" text,
  "quantidade" text,
  "data" date,
  "valor" double precision,
  "validacao" bigint,
  "status_financeiro" text,
  "material_id" bigint,
  "mao_de_obra_id" bigint,
  "locacao_id" bigint,
  "etapa_nome" text,
  CONSTRAINT "relatorio_cliente_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."relatorio_locacoes" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "obra_id" bigint NOT NULL,
  "equipamento" text NOT NULL,
  "quantidade" numeric(12,2) NOT NULL,
  "tipo_periodo" text NOT NULL,
  "periodo" integer NOT NULL,
  "solicitante" text NOT NULL,
  "data_coleta" date DEFAULT CURRENT_DATE NOT NULL,
  "data_vencimento" date,
  "valor" numeric(14,2) DEFAULT 0 NOT NULL,
  "status" text DEFAULT 'Solicitado'::text NOT NULL,
  "status_financeiro" text DEFAULT 'Aguardando pagamento'::text NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "validacao" integer DEFAULT 0 NOT NULL,
  "etapa_nome" text,
  CONSTRAINT "relatorio_locacoes_periodo_check" CHECK ((periodo > 0)),
  CONSTRAINT "relatorio_locacoes_pkey" PRIMARY KEY (id),
  CONSTRAINT "relatorio_locacoes_quantidade_check" CHECK ((quantidade > (0)::numeric)),
  CONSTRAINT "relatorio_locacoes_tipo_periodo_check" CHECK ((tipo_periodo = ANY (ARRAY['Diário'::text, 'Semanal'::text, 'Mensal'::text, 'Anual'::text])))
);

CREATE TABLE IF NOT EXISTS public."relatorio_mao_de_obra" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "obra_id" bigint,
  "tipo" text,
  "valor_cobrado" double precision,
  "data_solicitacao" date,
  "profissional" text,
  "valor_orcado" double precision,
  "valor_pago" double precision,
  "saldo" double precision,
  "validacao" bigint,
  "prestador_id" bigint,
  "classe_id" bigint,
  "etapa_nome" text,
  CONSTRAINT "relatorio_mao_de_obra_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."relatorio_materiais" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "obra_id" bigint,
  "material" text,
  "quantidade" text,
  "data_solicitacao" date,
  "status" text,
  "valor" double precision,
  "status_financeiro" text,
  "fornecedor_id" uuid,
  "data_vencimento" date,
  "etapa_nome" text,
  CONSTRAINT "relatorio_materiais_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."relatorios_diretoria" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "modalidade" text NOT NULL,
  "ano" integer NOT NULL,
  "mes" integer NOT NULL,
  "semana_ref" integer NOT NULL,
  "conteudo" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "criado_por" uuid,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  "semana_inicio" date NOT NULL,
  CONSTRAINT "relatorios_diretoria_mes_check" CHECK (((mes >= 1) AND (mes <= 12))),
  CONSTRAINT "relatorios_diretoria_modalidade_check" CHECK ((modalidade = ANY (ARRAY['obra'::text, 'financeiro'::text, 'compras'::text]))),
  CONSTRAINT "relatorios_diretoria_pkey" PRIMARY KEY (id),
  CONSTRAINT "relatorios_diretoria_semana_ref_check" CHECK (((semana_ref >= 1) AND (semana_ref <= 5))),
  CONSTRAINT "relatorios_diretoria_unique_modalidade_semana" UNIQUE (modalidade, semana_inicio)
);

CREATE TABLE IF NOT EXISTS public."reservas_sala" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "titulo" text NOT NULL,
  "cliente_nome" text,
  "inicio" timestamp with time zone NOT NULL,
  "fim" timestamp with time zone NOT NULL,
  "criado_por" uuid,
  "observacoes" text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "reservas_sala_duracao_minima" CHECK ((fim >= (inicio + '00:30:00'::interval))),
  CONSTRAINT "reservas_sala_fim_apos_inicio" CHECK ((fim > inicio)),
  CONSTRAINT "reservas_sala_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."saida" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "descricao" text,
  "forma" text,
  "valor" double precision,
  "data" date,
  "escritorio_id" uuid,
  "grupo_id" text,
  "validacao" integer,
  "escritorio" text DEFAULT 'Montezuma'::text,
  CONSTRAINT "saida_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."tarefa_progresso" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "tarefa_id" uuid NOT NULL,
  "usuario_id" uuid NOT NULL,
  "mensagem" text NOT NULL,
  "criado_em" timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  CONSTRAINT "tarefa_progresso_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."tarefa_responsaveis" (
  "tarefa_id" uuid NOT NULL,
  "usuario_id" uuid NOT NULL,
  CONSTRAINT "tarefa_responsaveis_pkey" PRIMARY KEY (tarefa_id, usuario_id)
);

CREATE TABLE IF NOT EXISTS public."tarefas" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "titulo" text NOT NULL,
  "descricao" text,
  "data_conclusao" date,
  "prioridade" text DEFAULT 'Média'::text,
  "criador_id" uuid,
  "criado_em" timestamp with time zone DEFAULT timezone('utc'::text, now()),
  "status" text DEFAULT 'Pendente'::text,
  "criador_nome" text,
  "criador_escritorio" text,
  "escritorio_id" uuid,
  "gestor_id" uuid,
  CONSTRAINT "tarefas_pkey" PRIMARY KEY (id),
  CONSTRAINT "tarefas_prioridade_check" CHECK ((prioridade = ANY (ARRAY['Alta'::text, 'Média'::text, 'Baixa'::text]))),
  CONSTRAINT "tarefas_status_check" CHECK ((status = ANY (ARRAY['Pendente'::text, 'Em Andamento'::text, 'Aguardando Validação'::text, 'Concluída'::text])))
);

CREATE TABLE IF NOT EXISTS public."usuarios" (
  "id" uuid NOT NULL,
  "nome" text,
  "tipo" text NOT NULL,
  "criado_em" timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  "escritorio" text DEFAULT 'Montezuma'::text,
  "escritorio_id" uuid,
  "subclasses" jsonb DEFAULT '[]'::jsonb NOT NULL,
  "assinatura_url" text,
  CONSTRAINT "usuarios_pkey" PRIMARY KEY (id),
  CONSTRAINT "usuarios_tipo_check" CHECK ((tipo = ANY (ARRAY['adm'::text, 'secretaria'::text, 'gestor_master'::text, 'diretoria'::text, 'suporte_ti'::text, 'encarregado'::text])))
);

CREATE TABLE IF NOT EXISTS public."whatsapp_messages" (
  "id" bigint DEFAULT nextval('whatsapp_messages_id_seq'::regclass) NOT NULL,
  "telefone" text NOT NULL,
  "role" text NOT NULL,
  "content" text NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "whatsapp_messages_pkey" PRIMARY KEY (id),
  CONSTRAINT "whatsapp_messages_role_check" CHECK ((role = ANY (ARRAY['user'::text, 'assistant'::text])))
);

CREATE TABLE IF NOT EXISTS public."whatsapp_sessions" (
  "telefone" text NOT NULL,
  "lista_bruta" text DEFAULT ''::text,
  "status" text DEFAULT 'aguardando_confirmacao'::text NOT NULL,
  "criado_em" timestamp with time zone DEFAULT now() NOT NULL,
  "obra_id" integer,
  "opcoes_obra" jsonb DEFAULT '[]'::jsonb NOT NULL,
  "itens_processados" jsonb DEFAULT '[]'::jsonb NOT NULL,
  "data_entrega" date,
  "rodada_obras" text,
  "rodada_confirmacao" text,
  CONSTRAINT "whatsapp_sessions_pkey" PRIMARY KEY (telefone)
);

-- Foreign keys (depois das tabelas por causa de referências cruzadas)
ALTER TABLE public."agenda" DROP CONSTRAINT IF EXISTS "agenda_cliente_id_fkey";
ALTER TABLE public."agenda" ADD CONSTRAINT "agenda_cliente_id_fkey" FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE SET NULL;
ALTER TABLE public."agenda" DROP CONSTRAINT IF EXISTS "agenda_criado_por_fkey";
ALTER TABLE public."agenda" ADD CONSTRAINT "agenda_criado_por_fkey" FOREIGN KEY (criado_por) REFERENCES usuarios(id) ON DELETE SET NULL;
ALTER TABLE public."agenda" DROP CONSTRAINT IF EXISTS "agenda_escritorio_id_fkey";
ALTER TABLE public."agenda" ADD CONSTRAINT "agenda_escritorio_id_fkey" FOREIGN KEY (escritorio_id) REFERENCES escritorios(id) ON DELETE RESTRICT;
ALTER TABLE public."agenda" DROP CONSTRAINT IF EXISTS "agenda_reserva_sala_id_fkey";
ALTER TABLE public."agenda" ADD CONSTRAINT "agenda_reserva_sala_id_fkey" FOREIGN KEY (reserva_sala_id) REFERENCES reservas_sala(id) ON DELETE SET NULL;
ALTER TABLE public."cliente_conversa_estado" DROP CONSTRAINT IF EXISTS "cliente_conversa_estado_obra_id_selecionada_fkey";
ALTER TABLE public."cliente_conversa_estado" ADD CONSTRAINT "cliente_conversa_estado_obra_id_selecionada_fkey" FOREIGN KEY (obra_id_selecionada) REFERENCES obras(id);
ALTER TABLE public."cliente_historico" DROP CONSTRAINT IF EXISTS "cliente_historico_author_id_fkey";
ALTER TABLE public."cliente_historico" ADD CONSTRAINT "cliente_historico_author_id_fkey" FOREIGN KEY (author_id) REFERENCES usuarios(id);
ALTER TABLE public."cliente_historico" DROP CONSTRAINT IF EXISTS "cliente_historico_obra_id_fkey";
ALTER TABLE public."cliente_historico" ADD CONSTRAINT "cliente_historico_obra_id_fkey" FOREIGN KEY (obra_id) REFERENCES obras(id) ON DELETE CASCADE;
ALTER TABLE public."cliente_mensagens" DROP CONSTRAINT IF EXISTS "cliente_mensagens_obra_id_fkey";
ALTER TABLE public."cliente_mensagens" ADD CONSTRAINT "cliente_mensagens_obra_id_fkey" FOREIGN KEY (obra_id) REFERENCES obras(id);
ALTER TABLE public."clientes" DROP CONSTRAINT IF EXISTS "clientes_obra_id_fkey";
ALTER TABLE public."clientes" ADD CONSTRAINT "clientes_obra_id_fkey" FOREIGN KEY (obra_id) REFERENCES obras(id);
ALTER TABLE public."contas_pagar_fornecedor" DROP CONSTRAINT IF EXISTS "contas_pagar_fornecedor_fornecedor_id_fkey";
ALTER TABLE public."contas_pagar_fornecedor" ADD CONSTRAINT "contas_pagar_fornecedor_fornecedor_id_fkey" FOREIGN KEY (fornecedor_id) REFERENCES fornecedores(id);
ALTER TABLE public."contas_pagar_fornecedor" DROP CONSTRAINT IF EXISTS "contas_pagar_fornecedor_material_id_fkey";
ALTER TABLE public."contas_pagar_fornecedor" ADD CONSTRAINT "contas_pagar_fornecedor_material_id_fkey" FOREIGN KEY (material_id) REFERENCES relatorio_materiais(id) ON DELETE CASCADE;
ALTER TABLE public."contas_pagar_fornecedor" DROP CONSTRAINT IF EXISTS "contas_pagar_fornecedor_obra_id_fkey";
ALTER TABLE public."contas_pagar_fornecedor" ADD CONSTRAINT "contas_pagar_fornecedor_obra_id_fkey" FOREIGN KEY (obra_id) REFERENCES obras(id);
ALTER TABLE public."cronograma_eventos" DROP CONSTRAINT IF EXISTS "cronograma_eventos_obra_id_fkey";
ALTER TABLE public."cronograma_eventos" ADD CONSTRAINT "cronograma_eventos_obra_id_fkey" FOREIGN KEY (obra_id) REFERENCES obras(id) ON DELETE CASCADE;
ALTER TABLE public."cronograma_eventos" DROP CONSTRAINT IF EXISTS "cronograma_eventos_user_id_fkey";
ALTER TABLE public."cronograma_eventos" ADD CONSTRAINT "cronograma_eventos_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id);
ALTER TABLE public."diario_obras" DROP CONSTRAINT IF EXISTS "diario_obras_obra_id_fkey";
ALTER TABLE public."diario_obras" ADD CONSTRAINT "diario_obras_obra_id_fkey" FOREIGN KEY (obra_id) REFERENCES obras(id) ON DELETE CASCADE;
ALTER TABLE public."diario_obras" DROP CONSTRAINT IF EXISTS "diario_obras_user_id_fkey";
ALTER TABLE public."diario_obras" ADD CONSTRAINT "diario_obras_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public."etapas" DROP CONSTRAINT IF EXISTS "etapas_obra_id_fkey";
ALTER TABLE public."etapas" ADD CONSTRAINT "etapas_obra_id_fkey" FOREIGN KEY (obra_id) REFERENCES obras(id);
ALTER TABLE public."obra_lote_itens" DROP CONSTRAINT IF EXISTS "obra_lote_itens_extrato_id_fkey";
ALTER TABLE public."obra_lote_itens" ADD CONSTRAINT "obra_lote_itens_extrato_id_fkey" FOREIGN KEY (extrato_id) REFERENCES relatorio_extrato(id) ON DELETE CASCADE;
ALTER TABLE public."obra_lote_itens" DROP CONSTRAINT IF EXISTS "obra_lote_itens_lote_id_fkey";
ALTER TABLE public."obra_lote_itens" ADD CONSTRAINT "obra_lote_itens_lote_id_fkey" FOREIGN KEY (lote_id) REFERENCES obra_lotes_pagamento(id) ON DELETE CASCADE;
ALTER TABLE public."obra_lotes_pagamento" DROP CONSTRAINT IF EXISTS "obra_lotes_pagamento_criado_por_fkey";
ALTER TABLE public."obra_lotes_pagamento" ADD CONSTRAINT "obra_lotes_pagamento_criado_por_fkey" FOREIGN KEY (criado_por) REFERENCES auth.users(id);
ALTER TABLE public."obra_lotes_pagamento" DROP CONSTRAINT IF EXISTS "obra_lotes_pagamento_obra_id_fkey";
ALTER TABLE public."obra_lotes_pagamento" ADD CONSTRAINT "obra_lotes_pagamento_obra_id_fkey" FOREIGN KEY (obra_id) REFERENCES obras(id) ON DELETE CASCADE;
ALTER TABLE public."obra_movimentacoes" DROP CONSTRAINT IF EXISTS "obra_movimentacoes_created_by_fkey";
ALTER TABLE public."obra_movimentacoes" ADD CONSTRAINT "obra_movimentacoes_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id);
ALTER TABLE public."obra_movimentacoes" DROP CONSTRAINT IF EXISTS "obra_movimentacoes_lote_pagamento_id_fkey";
ALTER TABLE public."obra_movimentacoes" ADD CONSTRAINT "obra_movimentacoes_lote_pagamento_id_fkey" FOREIGN KEY (lote_pagamento_id) REFERENCES obra_lotes_pagamento(id) ON DELETE SET NULL;
ALTER TABLE public."obra_movimentacoes" DROP CONSTRAINT IF EXISTS "obra_movimentacoes_obra_contra_id_fkey";
ALTER TABLE public."obra_movimentacoes" ADD CONSTRAINT "obra_movimentacoes_obra_contra_id_fkey" FOREIGN KEY (obra_contra_id) REFERENCES obras(id) ON DELETE SET NULL;
ALTER TABLE public."obra_movimentacoes" DROP CONSTRAINT IF EXISTS "obra_movimentacoes_obra_id_fkey";
ALTER TABLE public."obra_movimentacoes" ADD CONSTRAINT "obra_movimentacoes_obra_id_fkey" FOREIGN KEY (obra_id) REFERENCES obras(id) ON DELETE CASCADE;
ALTER TABLE public."obra_pedido_grupos_compra" DROP CONSTRAINT IF EXISTS "obra_pedido_grupos_compra_pedido_id_fkey";
ALTER TABLE public."obra_pedido_grupos_compra" ADD CONSTRAINT "obra_pedido_grupos_compra_pedido_id_fkey" FOREIGN KEY (pedido_id) REFERENCES obra_pedidos(id) ON DELETE CASCADE;
ALTER TABLE public."obra_pedido_itens" DROP CONSTRAINT IF EXISTS "obra_pedido_itens_fornecedor_id_fkey";
ALTER TABLE public."obra_pedido_itens" ADD CONSTRAINT "obra_pedido_itens_fornecedor_id_fkey" FOREIGN KEY (fornecedor_id) REFERENCES fornecedores(id) ON DELETE SET NULL;
ALTER TABLE public."obra_pedido_itens" DROP CONSTRAINT IF EXISTS "obra_pedido_itens_grupo_compra_id_fkey";
ALTER TABLE public."obra_pedido_itens" ADD CONSTRAINT "obra_pedido_itens_grupo_compra_id_fkey" FOREIGN KEY (grupo_compra_id) REFERENCES obra_pedido_grupos_compra(id) ON DELETE RESTRICT;
ALTER TABLE public."obra_pedido_itens" DROP CONSTRAINT IF EXISTS "obra_pedido_itens_pedido_id_fkey";
ALTER TABLE public."obra_pedido_itens" ADD CONSTRAINT "obra_pedido_itens_pedido_id_fkey" FOREIGN KEY (pedido_id) REFERENCES obra_pedidos(id) ON DELETE CASCADE;
ALTER TABLE public."obra_pedidos" DROP CONSTRAINT IF EXISTS "obra_pedidos_obra_id_fkey";
ALTER TABLE public."obra_pedidos" ADD CONSTRAINT "obra_pedidos_obra_id_fkey" FOREIGN KEY (obra_id) REFERENCES obras(id) ON DELETE CASCADE;
ALTER TABLE public."obra_whatsapp_config" DROP CONSTRAINT IF EXISTS "obra_whatsapp_config_obra_id_fkey";
ALTER TABLE public."obra_whatsapp_config" ADD CONSTRAINT "obra_whatsapp_config_obra_id_fkey" FOREIGN KEY (obra_id) REFERENCES obras(id);
ALTER TABLE public."obras" DROP CONSTRAINT IF EXISTS "obras_cliente_id_fkey";
ALTER TABLE public."obras" ADD CONSTRAINT "obras_cliente_id_fkey" FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE RESTRICT;
ALTER TABLE public."obras" DROP CONSTRAINT IF EXISTS "obras_responsavel_id_fkey";
ALTER TABLE public."obras" ADD CONSTRAINT "obras_responsavel_id_fkey" FOREIGN KEY (responsavel_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public."ordens_servico" DROP CONSTRAINT IF EXISTS "ordens_servico_concluido_por_id_fkey";
ALTER TABLE public."ordens_servico" ADD CONSTRAINT "ordens_servico_concluido_por_id_fkey" FOREIGN KEY (concluido_por_id) REFERENCES usuarios(id);
ALTER TABLE public."ordens_servico" DROP CONSTRAINT IF EXISTS "ordens_servico_criador_id_fkey";
ALTER TABLE public."ordens_servico" ADD CONSTRAINT "ordens_servico_criador_id_fkey" FOREIGN KEY (criador_id) REFERENCES usuarios(id);
ALTER TABLE public."ordens_servico" DROP CONSTRAINT IF EXISTS "ordens_servico_responsavel_id_fkey";
ALTER TABLE public."ordens_servico" ADD CONSTRAINT "ordens_servico_responsavel_id_fkey" FOREIGN KEY (responsavel_id) REFERENCES usuarios(id);
ALTER TABLE public."prestadores_classes" DROP CONSTRAINT IF EXISTS "prestadores_classes_classe_id_fkey";
ALTER TABLE public."prestadores_classes" ADD CONSTRAINT "prestadores_classes_classe_id_fkey" FOREIGN KEY (classe_id) REFERENCES classes_prestadores(id) ON DELETE CASCADE;
ALTER TABLE public."prestadores_classes" DROP CONSTRAINT IF EXISTS "prestadores_classes_prestador_id_fkey";
ALTER TABLE public."prestadores_classes" ADD CONSTRAINT "prestadores_classes_prestador_id_fkey" FOREIGN KEY (prestador_id) REFERENCES prestadores(id) ON DELETE CASCADE;
ALTER TABLE public."relatorio_extrato" DROP CONSTRAINT IF EXISTS "relatorio_cliente_obra_id_fkey";
ALTER TABLE public."relatorio_extrato" ADD CONSTRAINT "relatorio_cliente_obra_id_fkey" FOREIGN KEY (obra_id) REFERENCES obras(id) ON DELETE CASCADE;
ALTER TABLE public."relatorio_extrato" DROP CONSTRAINT IF EXISTS "relatorio_extrato_locacao_id_fkey";
ALTER TABLE public."relatorio_extrato" ADD CONSTRAINT "relatorio_extrato_locacao_id_fkey" FOREIGN KEY (locacao_id) REFERENCES relatorio_locacoes(id) ON DELETE CASCADE;
ALTER TABLE public."relatorio_locacoes" DROP CONSTRAINT IF EXISTS "relatorio_locacoes_obra_id_fkey";
ALTER TABLE public."relatorio_locacoes" ADD CONSTRAINT "relatorio_locacoes_obra_id_fkey" FOREIGN KEY (obra_id) REFERENCES obras(id) ON DELETE CASCADE;
ALTER TABLE public."relatorio_mao_de_obra" DROP CONSTRAINT IF EXISTS "relatorio_mao_de_obra_classe_id_fkey";
ALTER TABLE public."relatorio_mao_de_obra" ADD CONSTRAINT "relatorio_mao_de_obra_classe_id_fkey" FOREIGN KEY (classe_id) REFERENCES classes_prestadores(id);
ALTER TABLE public."relatorio_mao_de_obra" DROP CONSTRAINT IF EXISTS "relatorio_mao_de_obra_obra_id_fkey";
ALTER TABLE public."relatorio_mao_de_obra" ADD CONSTRAINT "relatorio_mao_de_obra_obra_id_fkey" FOREIGN KEY (obra_id) REFERENCES obras(id);
ALTER TABLE public."relatorio_mao_de_obra" DROP CONSTRAINT IF EXISTS "relatorio_mao_de_obra_prestador_id_fkey";
ALTER TABLE public."relatorio_mao_de_obra" ADD CONSTRAINT "relatorio_mao_de_obra_prestador_id_fkey" FOREIGN KEY (prestador_id) REFERENCES prestadores(id);
ALTER TABLE public."relatorio_materiais" DROP CONSTRAINT IF EXISTS "relatorio_materiais_fornecedor_id_fkey";
ALTER TABLE public."relatorio_materiais" ADD CONSTRAINT "relatorio_materiais_fornecedor_id_fkey" FOREIGN KEY (fornecedor_id) REFERENCES fornecedores(id);
ALTER TABLE public."relatorio_materiais" DROP CONSTRAINT IF EXISTS "relatorio_materiais_obra_id_fkey";
ALTER TABLE public."relatorio_materiais" ADD CONSTRAINT "relatorio_materiais_obra_id_fkey" FOREIGN KEY (obra_id) REFERENCES obras(id);
ALTER TABLE public."relatorios_diretoria" DROP CONSTRAINT IF EXISTS "relatorios_diretoria_criado_por_fkey";
ALTER TABLE public."relatorios_diretoria" ADD CONSTRAINT "relatorios_diretoria_criado_por_fkey" FOREIGN KEY (criado_por) REFERENCES auth.users(id);
ALTER TABLE public."reservas_sala" DROP CONSTRAINT IF EXISTS "reservas_sala_criado_por_fkey";
ALTER TABLE public."reservas_sala" ADD CONSTRAINT "reservas_sala_criado_por_fkey" FOREIGN KEY (criado_por) REFERENCES usuarios(id);
ALTER TABLE public."tarefa_progresso" DROP CONSTRAINT IF EXISTS "tarefa_progresso_tarefa_id_fkey";
ALTER TABLE public."tarefa_progresso" ADD CONSTRAINT "tarefa_progresso_tarefa_id_fkey" FOREIGN KEY (tarefa_id) REFERENCES tarefas(id) ON DELETE CASCADE;
ALTER TABLE public."tarefa_progresso" DROP CONSTRAINT IF EXISTS "tarefa_progresso_usuario_id_fkey";
ALTER TABLE public."tarefa_progresso" ADD CONSTRAINT "tarefa_progresso_usuario_id_fkey" FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE;
ALTER TABLE public."tarefa_responsaveis" DROP CONSTRAINT IF EXISTS "tarefa_responsaveis_tarefa_id_fkey";
ALTER TABLE public."tarefa_responsaveis" ADD CONSTRAINT "tarefa_responsaveis_tarefa_id_fkey" FOREIGN KEY (tarefa_id) REFERENCES tarefas(id) ON DELETE CASCADE;
ALTER TABLE public."tarefa_responsaveis" DROP CONSTRAINT IF EXISTS "tarefa_responsaveis_usuario_id_fkey";
ALTER TABLE public."tarefa_responsaveis" ADD CONSTRAINT "tarefa_responsaveis_usuario_id_fkey" FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE;
ALTER TABLE public."tarefas" DROP CONSTRAINT IF EXISTS "tarefas_criador_id_fkey";
ALTER TABLE public."tarefas" ADD CONSTRAINT "tarefas_criador_id_fkey" FOREIGN KEY (criador_id) REFERENCES usuarios(id) ON DELETE SET NULL;
ALTER TABLE public."tarefas" DROP CONSTRAINT IF EXISTS "tarefas_gestor_id_fkey";
ALTER TABLE public."tarefas" ADD CONSTRAINT "tarefas_gestor_id_fkey" FOREIGN KEY (gestor_id) REFERENCES usuarios(id) ON DELETE SET NULL;
ALTER TABLE public."usuarios" DROP CONSTRAINT IF EXISTS "fk_usuarios_escritorio";
ALTER TABLE public."usuarios" ADD CONSTRAINT "fk_usuarios_escritorio" FOREIGN KEY (escritorio_id) REFERENCES escritorios(id);
ALTER TABLE public."usuarios" DROP CONSTRAINT IF EXISTS "usuarios_id_fkey";
ALTER TABLE public."usuarios" ADD CONSTRAINT "usuarios_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public."whatsapp_sessions" DROP CONSTRAINT IF EXISTS "whatsapp_sessions_obra_id_fkey";
ALTER TABLE public."whatsapp_sessions" ADD CONSTRAINT "whatsapp_sessions_obra_id_fkey" FOREIGN KEY (obra_id) REFERENCES obras(id);

ALTER SEQUENCE public.cliente_mensagens_id_seq OWNED BY public.cliente_mensagens.id;
ALTER SEQUENCE public.obra_whatsapp_config_id_seq OWNED BY public.obra_whatsapp_config.id;
ALTER SEQUENCE public.whatsapp_messages_id_seq OWNED BY public.whatsapp_messages.id;

CREATE INDEX IF NOT EXISTS idx_agenda_cliente ON public.agenda USING btree (cliente_id);
CREATE INDEX IF NOT EXISTS idx_agenda_data_hora ON public.agenda USING btree (data_hora);
CREATE INDEX IF NOT EXISTS idx_agenda_escritorio_data ON public.agenda USING btree (escritorio_id, data_hora);
CREATE INDEX IF NOT EXISTS idx_agenda_reserva_sala_id ON public.agenda USING btree (reserva_sala_id) WHERE (reserva_sala_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_agenda_status ON public.agenda USING btree (status);
CREATE INDEX IF NOT EXISTS idx_cliente_historico_author_id ON public.cliente_historico USING btree (author_id);
CREATE INDEX IF NOT EXISTS idx_cliente_historico_obra_data ON public.cliente_historico USING btree (obra_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_cliente_mensagens_telefone_created_at ON public.cliente_mensagens USING btree (telefone, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_contas_pagar_fornecedor_fornecedor ON public.contas_pagar_fornecedor USING btree (fornecedor_id);
CREATE INDEX IF NOT EXISTS idx_contas_pagar_fornecedor_obra ON public.contas_pagar_fornecedor USING btree (obra_id);
CREATE INDEX IF NOT EXISTS idx_contas_pagar_fornecedor_status ON public.contas_pagar_fornecedor USING btree (status_pagamento);
CREATE INDEX IF NOT EXISTS idx_contas_pagar_fornecedor_vencimento ON public.contas_pagar_fornecedor USING btree (data_vencimento);
CREATE INDEX IF NOT EXISTS idx_obra_lote_itens_extrato ON public.obra_lote_itens USING btree (extrato_id);
CREATE INDEX IF NOT EXISTS idx_obra_lote_itens_lote ON public.obra_lote_itens USING btree (lote_id);
CREATE INDEX IF NOT EXISTS idx_obra_lotes_pagamento_obra ON public.obra_lotes_pagamento USING btree (obra_id, status, data_criacao DESC);
CREATE INDEX IF NOT EXISTS idx_obra_movimentacoes_grupo ON public.obra_movimentacoes USING btree (transferencia_grupo_id) WHERE (transferencia_grupo_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_obra_movimentacoes_obra_data ON public.obra_movimentacoes USING btree (obra_id, data DESC, created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS obra_movimentacoes_lote_pagamento_unique ON public.obra_movimentacoes USING btree (lote_pagamento_id) WHERE (lote_pagamento_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS obra_pedido_grupos_compra_pedido_id_idx ON public.obra_pedido_grupos_compra USING btree (pedido_id);
CREATE INDEX IF NOT EXISTS obra_pedido_itens_grupo_compra_id_idx ON public.obra_pedido_itens USING btree (grupo_compra_id);
CREATE INDEX IF NOT EXISTS obra_pedido_itens_pedido_id_idx ON public.obra_pedido_itens USING btree (pedido_id);
CREATE INDEX IF NOT EXISTS obra_pedidos_created_at_idx ON public.obra_pedidos USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS obra_pedidos_obra_id_idx ON public.obra_pedidos USING btree (obra_id);
CREATE UNIQUE INDEX IF NOT EXISTS obra_pedidos_obra_id_numero_key ON public.obra_pedidos USING btree (obra_id, numero);
CREATE INDEX IF NOT EXISTS idx_obra_whatsapp_config_resumo_pendente ON public.obra_whatsapp_config USING btree (recebe_atualizacoes, ultimo_resumo_enviado_em);
CREATE INDEX IF NOT EXISTS idx_obras_responsavel_id ON public.obras USING btree (responsavel_id);
CREATE INDEX IF NOT EXISTS idx_orcamentos_escritorio_numero_proposta ON public.orcamentos USING btree (escritorio_id, numero_proposta) WHERE (numero_proposta IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_ordens_servico_criador ON public.ordens_servico USING btree (criador_id);
CREATE INDEX IF NOT EXISTS idx_ordens_servico_escritorio_status ON public.ordens_servico USING btree (escritorio_id, status, data_emissao DESC);
CREATE INDEX IF NOT EXISTS idx_ordens_servico_responsavel_status ON public.ordens_servico USING btree (responsavel_id, status);
CREATE INDEX IF NOT EXISTS idx_projecoes_data_proposta ON public.projecoes USING btree (data_proposta DESC);
CREATE INDEX IF NOT EXISTS idx_relatorio_extrato_obra_etapa ON public.relatorio_extrato USING btree (obra_id, etapa_nome);
CREATE INDEX IF NOT EXISTS relatorio_extrato_locacao_id_idx ON public.relatorio_extrato USING btree (locacao_id);
CREATE INDEX IF NOT EXISTS idx_relatorio_locacoes_obra_etapa ON public.relatorio_locacoes USING btree (obra_id, etapa_nome);
CREATE INDEX IF NOT EXISTS relatorio_locacoes_created_at_idx ON public.relatorio_locacoes USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS relatorio_locacoes_obra_id_idx ON public.relatorio_locacoes USING btree (obra_id);
CREATE INDEX IF NOT EXISTS idx_relatorio_mao_de_obra_obra_etapa ON public.relatorio_mao_de_obra USING btree (obra_id, etapa_nome);
CREATE INDEX IF NOT EXISTS idx_relatorio_materiais_obra_etapa ON public.relatorio_materiais USING btree (obra_id, etapa_nome);
CREATE INDEX IF NOT EXISTS idx_relatorios_diretoria_periodo ON public.relatorios_diretoria USING btree (ano, mes);
CREATE INDEX IF NOT EXISTS idx_relatorios_diretoria_semana_inicio ON public.relatorios_diretoria USING btree (semana_inicio);
CREATE INDEX IF NOT EXISTS idx_reservas_sala_inicio_fim ON public.reservas_sala USING btree (inicio, fim);
CREATE INDEX IF NOT EXISTS idx_whatsapp_messages_telefone_created ON public.whatsapp_messages USING btree (telefone, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_whatsapp_sessions_status ON public.whatsapp_sessions USING btree (status);

CREATE OR REPLACE FUNCTION private.get_obra_historico_for_cliente(p_obra_id bigint)
 RETURNS TABLE(id uuid, obra_id bigint, author_nome text, mensagem text, created_at timestamp with time zone)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'private', 'public'
AS $function$
begin
  if auth.uid() is null then
    raise exception 'Not authenticated';
  end if;

  if not exists (
    select 1
    from public.obras o
    inner join public.clientes c on c.id = o.cliente_id
    where o.id = p_obra_id
      and c.auth_user_id is not null
      and c.auth_user_id = auth.uid()
  ) then
    raise exception 'Forbidden';
  end if;

  return query
  select ch.id, ch.obra_id, ch.author_nome, ch.mensagem, ch.created_at
  from public.cliente_historico ch
  where ch.obra_id = p_obra_id
  order by ch.created_at desc;
end;
$function$;

CREATE OR REPLACE FUNCTION public.agenda_set_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  new.updated_at := now();
  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.auth_user_escritorio()
 RETURNS text
 LANGUAGE sql
 SECURITY DEFINER
AS $function$
  SELECT escritorio FROM public.usuarios WHERE id = auth.uid() LIMIT 1;
$function$;

CREATE OR REPLACE FUNCTION public.auth_user_tipo()
 RETURNS text
 LANGUAGE sql
 SECURITY DEFINER
AS $function$
  SELECT tipo FROM public.usuarios WHERE id = auth.uid() LIMIT 1;
$function$;

CREATE OR REPLACE FUNCTION public.buscar_dados_cliente(p_nome text, p_bairro text)
 RETURNS SETOF clientes
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  RETURN QUERY
  SELECT * FROM public.clientes
  WHERE lower(trim(nome)) = lower(trim(p_nome))
    AND lower(trim(bairro_obra)) = lower(trim(p_bairro)); -- Corrigido para bairro_obra
END;
$function$;

CREATE OR REPLACE FUNCTION public.check_extrato_not_in_open_lote()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM obra_lote_itens oli
    JOIN obra_lotes_pagamento olp ON olp.id = oli.lote_id
    WHERE oli.extrato_id = NEW.extrato_id
      AND olp.status IN ('pendente', 'parcial')
      AND oli.lote_id IS DISTINCT FROM NEW.lote_id
  ) THEN
    RAISE EXCEPTION 'Item do extrato já pertence a um lote de pagamento aberto';
  END IF;
  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.check_reservas_sala_no_overlap()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM reservas_sala r
    WHERE r.id IS DISTINCT FROM NEW.id
      AND r.inicio < NEW.fim
      AND r.fim > NEW.inicio
  ) THEN
    RAISE EXCEPTION 'reservas_sala_no_overlap: sala ocupada neste horário'
      USING ERRCODE = '23P01';
  END IF;
  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.estornar_saida_pagamento_lote(p_lote_id uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Não autenticado';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM usuarios u
    WHERE u.id = auth.uid()
      AND u.tipo IN ('diretoria', 'gestor_master', 'suporte_ti', 'encarregado')
  ) THEN
    RAISE EXCEPTION 'Sem permissão para estornar saída de pagamento';
  END IF;

  DELETE FROM obra_movimentacoes
  WHERE lote_pagamento_id = p_lote_id
    AND tipo = 'saida_pagamento';
END;
$function$;

CREATE OR REPLACE FUNCTION public.listar_usuarios_responsaveis_tarefa()
 RETURNS TABLE(id text, nome text, escritorio text, tipo text)
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Sessão inválida (auth.uid() nulo)'
      USING ERRCODE = '42501';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM public.usuarios me
    WHERE me.id::text = auth.uid()::text
      AND lower(trim(coalesce(me.tipo, ''))) IN ('gestor_master', 'diretoria')
  ) THEN
    RAISE EXCEPTION 'Sem permissão para listar responsáveis'
      USING ERRCODE = '42501';
  END IF;

  RETURN QUERY
  SELECT
    u.id::text,
    u.nome,
    u.escritorio,
    u.tipo
  FROM public.usuarios u
  WHERE lower(trim(coalesce(u.tipo, ''))) <> 'gestor_master'
  ORDER BY u.nome;
END;
$function$;

CREATE OR REPLACE FUNCTION public.obter_cliente_por_id(p_id bigint)
 RETURNS SETOF clientes
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  RETURN QUERY 
  SELECT * FROM public.clientes 
  WHERE id = p_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.pode_acessar_escritorio(p_escritorio_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (
    select 1
      from public.usuarios u
     where u.id = auth.uid()
       and (
         u.escritorio_id = p_escritorio_id
         or u.tipo in ('gestor_master', 'diretoria')
       )
  );
$function$;

CREATE OR REPLACE FUNCTION public.registrar_emprestimo_pessoa(p_obra_id bigint, p_pessoa text, p_sentido text, p_valor numeric, p_descricao text DEFAULT NULL::text, p_data date DEFAULT CURRENT_DATE)
 RETURNS uuid
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
DECLARE
  v_saldo numeric;
  v_grupo uuid := gen_random_uuid();
  v_data date := COALESCE(p_data, CURRENT_DATE);
  v_pessoa text := trim(COALESCE(p_pessoa, ''));
  v_tipo text;
BEGIN
  IF p_valor IS NULL OR p_valor <= 0 THEN
    RAISE EXCEPTION 'Valor deve ser maior que zero';
  END IF;
  IF p_obra_id IS NULL THEN
    RAISE EXCEPTION 'Obra é obrigatória';
  END IF;
  IF v_pessoa = '' THEN
    RAISE EXCEPTION 'Nome da pessoa é obrigatório';
  END IF;
  IF p_sentido IS NULL OR p_sentido NOT IN ('emprestar', 'receber') THEN
    RAISE EXCEPTION 'Sentido deve ser emprestar ou receber';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM obras WHERE id = p_obra_id) THEN
    RAISE EXCEPTION 'Obra não encontrada';
  END IF;

  IF p_sentido = 'emprestar' THEN
    v_tipo := 'transferencia_saida';

    PERFORM pg_advisory_xact_lock(
      hashtextextended('obra_caixa:' || p_obra_id::text, 0)
    );

    SELECT COALESCE(SUM(
      CASE
        WHEN tipo IN ('entrada', 'transferencia_entrada') THEN valor
        WHEN tipo IN ('transferencia_saida', 'saida_pagamento') THEN -valor
        ELSE 0
      END
    ), 0)
    INTO v_saldo
    FROM obra_movimentacoes
    WHERE obra_id = p_obra_id;

    IF v_saldo < p_valor THEN
      RAISE EXCEPTION 'Saldo insuficiente na obra (disponível: %)', v_saldo;
    END IF;
  ELSE
    v_tipo := 'transferencia_entrada';
  END IF;

  INSERT INTO obra_movimentacoes (
    obra_id, tipo, valor, descricao, data,
    transferencia_grupo_id, obra_contra_id, pessoa_contra, created_by
  ) VALUES (
    p_obra_id, v_tipo, p_valor, p_descricao, v_data,
    v_grupo, NULL, v_pessoa, auth.uid()
  );

  RETURN v_grupo;
END;
$function$;

CREATE OR REPLACE FUNCTION public.registrar_saida_pagamento_lote(p_lote_id uuid)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_lote RECORD;
  v_existente uuid;
  v_id uuid;
  v_valor numeric;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Não autenticado';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM usuarios u
    WHERE u.id = auth.uid()
      AND u.tipo IN ('diretoria', 'gestor_master', 'suporte_ti', 'encarregado')
  ) THEN
    RAISE EXCEPTION 'Sem permissão para registrar saída de pagamento';
  END IF;

  SELECT id, obra_id, numero, total, status
  INTO v_lote
  FROM obra_lotes_pagamento
  WHERE id = p_lote_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Lote não encontrado';
  END IF;

  SELECT id INTO v_existente
  FROM obra_movimentacoes
  WHERE lote_pagamento_id = p_lote_id
  LIMIT 1;

  IF v_existente IS NOT NULL THEN
    RETURN v_existente;
  END IF;

  v_valor := COALESCE(v_lote.total, 0);
  IF v_valor <= 0 THEN
    RAISE EXCEPTION 'Lote sem valor para debitar do caixa';
  END IF;

  INSERT INTO obra_movimentacoes (
    obra_id, tipo, valor, descricao, data,
    lote_pagamento_id, created_by
  ) VALUES (
    v_lote.obra_id,
    'saida_pagamento',
    v_valor,
    'Pagamento extrato #' || v_lote.numero::text,
    CURRENT_DATE,
    p_lote_id,
    auth.uid()
  )
  RETURNING id INTO v_id;

  RETURN v_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.set_projecoes_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  new.updated_at = now();
  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.set_reservas_sala_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.set_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  new.updated_at = now();
  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.transferir_saldo_obra(p_obra_origem_id bigint, p_obra_destino_id bigint, p_valor numeric, p_descricao text DEFAULT NULL::text, p_data date DEFAULT CURRENT_DATE)
 RETURNS uuid
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
DECLARE
  v_saldo numeric;
  v_grupo uuid := gen_random_uuid();
  v_data date := COALESCE(p_data, CURRENT_DATE);
BEGIN
  IF p_valor IS NULL OR p_valor <= 0 THEN
    RAISE EXCEPTION 'Valor deve ser maior que zero';
  END IF;
  IF p_obra_origem_id IS NULL OR p_obra_destino_id IS NULL THEN
    RAISE EXCEPTION 'Obras de origem e destino são obrigatórias';
  END IF;
  IF p_obra_origem_id = p_obra_destino_id THEN
    RAISE EXCEPTION 'Origem e destino devem ser obras distintas';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM obras WHERE id = p_obra_origem_id) THEN
    RAISE EXCEPTION 'Obra de origem não encontrada';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM obras WHERE id = p_obra_destino_id) THEN
    RAISE EXCEPTION 'Obra de destino não encontrada';
  END IF;

  PERFORM pg_advisory_xact_lock(
    hashtextextended('obra_caixa:' || p_obra_origem_id::text, 0)
  );

  SELECT COALESCE(SUM(
    CASE
      WHEN tipo IN ('entrada', 'transferencia_entrada') THEN valor
      WHEN tipo IN ('transferencia_saida', 'saida_pagamento') THEN -valor
      ELSE 0
    END
  ), 0)
  INTO v_saldo
  FROM obra_movimentacoes
  WHERE obra_id = p_obra_origem_id;

  IF v_saldo < p_valor THEN
    RAISE EXCEPTION 'Saldo insuficiente na obra de origem (disponível: %)', v_saldo;
  END IF;

  INSERT INTO obra_movimentacoes (
    obra_id, tipo, valor, descricao, data,
    transferencia_grupo_id, obra_contra_id, created_by
  ) VALUES
    (
      p_obra_origem_id, 'transferencia_saida', p_valor, p_descricao, v_data,
      v_grupo, p_obra_destino_id, auth.uid()
    ),
    (
      p_obra_destino_id, 'transferencia_entrada', p_valor, p_descricao, v_data,
      v_grupo, p_obra_origem_id, auth.uid()
    );

  RETURN v_grupo;
END;
$function$;

CREATE OR REPLACE FUNCTION public.usuario_eh_gestor_sistema()
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT EXISTS (
    SELECT 1 FROM usuarios u
    WHERE u.id = auth.uid()
      AND u.tipo IN ('diretoria', 'gestor_master')
  );
$function$;

CREATE OR REPLACE FUNCTION public.usuario_pode_ver_ordem_servico(os ordens_servico)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT EXISTS (
    SELECT 1 FROM usuarios u
    WHERE u.id = auth.uid()
      AND (
        u.tipo = 'gestor_master'
        OR u.subclasses @> '["gestor_os"]'::jsonb
        OR os.criador_id = auth.uid()
        OR os.responsavel_id = auth.uid()
      )
  );
$function$;

CREATE OR REPLACE FUNCTION public.usuario_subclasses_contem(subclasse text)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT COALESCE(
    (
      SELECT u.subclasses @> jsonb_build_array(subclasse)
      FROM usuarios u
      WHERE u.id = auth.uid()
    ),
    false
  );
$function$;

CREATE OR REPLACE FUNCTION public.validar_login_cliente(nome_digitado text, local_digitado text)
 RETURNS json
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
declare
  resultado json;
begin
  select json_build_object(
    'id', id, 
    'cliente', cliente, 
    'local', local, -- Tenha certeza que sua coluna se chama 'local' mesmo, e não 'bairro'
    'role', 'cliente'
  )
  into resultado
  from public.obras
  where 
    -- O 'trim' remove espaços antes e depois. O 'lower' ignora maiúsculas.
    lower(trim(cliente)) = lower(trim(nome_digitado)) 
    and lower(trim(local)) = lower(trim(local_digitado));
  
  return resultado;
end;
$function$;

CREATE OR REPLACE FUNCTION public.get_obra_historico_for_cliente(p_obra_id bigint)
 RETURNS TABLE(id uuid, obra_id bigint, author_nome text, mensagem text, created_at timestamp with time zone)
 LANGUAGE sql
 SET search_path TO 'public', 'private'
AS $function$
  select *
  from private.get_obra_historico_for_cliente(p_obra_id);
$function$;

CREATE OR REPLACE FUNCTION public.usuario_pode_editar_usuario(alvo usuarios)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT
    auth.uid() IS NOT NULL
    AND (
      alvo.id = auth.uid()
      OR (
        usuario_eh_gestor_sistema()
        AND alvo.tipo NOT IN ('diretoria', 'gestor_master')
      )
    );
$function$;

CREATE OR REPLACE FUNCTION public.usuario_pode_excluir_ordem_servico(os ordens_servico)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT EXISTS (
    SELECT 1 FROM usuarios u
    WHERE u.id = auth.uid()
      AND usuario_pode_ver_ordem_servico(os)
      AND (
        u.tipo = 'gestor_master'
        OR u.subclasses @> '["gestor_os"]'::jsonb
        OR (os.criador_id = auth.uid() AND os.status = 'pendente')
      )
  );
$function$;

ALTER TABLE public."agenda" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."classes_prestadores" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."cliente_conversa_estado" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."cliente_historico" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."cliente_mensagens" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."clientes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."contas_pagar_fornecedor" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."cronograma_eventos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."diario_obras" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."entradas" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."escritorios" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."etapas" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."fornecedores" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."obra_lote_itens" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."obra_lotes_pagamento" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."obra_movimentacoes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."obra_pedido_grupos_compra" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."obra_pedido_itens" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."obra_pedidos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."obra_whatsapp_config" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."obras" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."orcamentos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."ordens_servico" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."prestadores" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."prestadores_classes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."projecoes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."relatorio_extrato" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."relatorio_locacoes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."relatorio_mao_de_obra" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."relatorio_materiais" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."relatorios_diretoria" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."reservas_sala" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."saida" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."tarefa_progresso" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."tarefa_responsaveis" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."tarefas" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."usuarios" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."whatsapp_messages" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."whatsapp_sessions" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "agenda_delete_tenant" ON public."agenda";
CREATE POLICY "agenda_delete_tenant" ON public."agenda"
  AS PERMISSIVE
  FOR DELETE
  TO authenticated
  USING (pode_acessar_escritorio(escritorio_id));

DROP POLICY IF EXISTS "agenda_insert_tenant" ON public."agenda";
CREATE POLICY "agenda_insert_tenant" ON public."agenda"
  AS PERMISSIVE
  FOR INSERT
  TO authenticated
  WITH CHECK (pode_acessar_escritorio(escritorio_id));

DROP POLICY IF EXISTS "agenda_select_tenant" ON public."agenda";
CREATE POLICY "agenda_select_tenant" ON public."agenda"
  AS PERMISSIVE
  FOR SELECT
  TO authenticated
  USING (pode_acessar_escritorio(escritorio_id));

DROP POLICY IF EXISTS "agenda_update_tenant" ON public."agenda";
CREATE POLICY "agenda_update_tenant" ON public."agenda"
  AS PERMISSIVE
  FOR UPDATE
  TO authenticated
  USING (pode_acessar_escritorio(escritorio_id))
  WITH CHECK (pode_acessar_escritorio(escritorio_id));

DROP POLICY IF EXISTS "Acesso Global Classes" ON public."classes_prestadores";
CREATE POLICY "Acesso Global Classes" ON public."classes_prestadores"
  AS PERMISSIVE
  FOR ALL
  TO public
  USING ((auth.role() = 'authenticated'::text));

DROP POLICY IF EXISTS "cliente_historico_delete_staff_own" ON public."cliente_historico";
CREATE POLICY "cliente_historico_delete_staff_own" ON public."cliente_historico"
  AS PERMISSIVE
  FOR DELETE
  TO authenticated
  USING (((author_id = auth.uid()) AND (EXISTS ( SELECT 1
   FROM usuarios u
  WHERE ((u.id = auth.uid()) AND (u.tipo IS DISTINCT FROM 'cliente'::text))))));

DROP POLICY IF EXISTS "cliente_historico_insert_staff" ON public."cliente_historico";
CREATE POLICY "cliente_historico_insert_staff" ON public."cliente_historico"
  AS PERMISSIVE
  FOR INSERT
  TO authenticated
  WITH CHECK (((author_id = auth.uid()) AND (EXISTS ( SELECT 1
   FROM usuarios u
  WHERE ((u.id = auth.uid()) AND (u.tipo IS DISTINCT FROM 'cliente'::text))))));

DROP POLICY IF EXISTS "cliente_historico_select_public_obra" ON public."cliente_historico";
CREATE POLICY "cliente_historico_select_public_obra" ON public."cliente_historico"
  AS PERMISSIVE
  FOR SELECT
  TO anon
  USING ((EXISTS ( SELECT 1
   FROM obras o
  WHERE ((o.id = cliente_historico.obra_id) AND ((o.active IS NULL) OR (lower(TRIM(BOTH FROM o.active)) <> ALL (ARRAY['false'::text, 'f'::text, '0'::text, 'no'::text, 'não'::text, 'nao'::text, 'inativo'::text, 'inactive'::text])))))));

DROP POLICY IF EXISTS "cliente_historico_select_staff" ON public."cliente_historico";
CREATE POLICY "cliente_historico_select_staff" ON public."cliente_historico"
  AS PERMISSIVE
  FOR SELECT
  TO public
  USING (true);

DROP POLICY IF EXISTS "cliente_historico_update_staff_own" ON public."cliente_historico";
CREATE POLICY "cliente_historico_update_staff_own" ON public."cliente_historico"
  AS PERMISSIVE
  FOR UPDATE
  TO authenticated
  USING (((author_id = auth.uid()) AND (EXISTS ( SELECT 1
   FROM usuarios u
  WHERE ((u.id = auth.uid()) AND (u.tipo IS DISTINCT FROM 'cliente'::text))))))
  WITH CHECK (((author_id = auth.uid()) AND (EXISTS ( SELECT 1
   FROM usuarios u
  WHERE ((u.id = auth.uid()) AND (u.tipo IS DISTINCT FROM 'cliente'::text))))));

DROP POLICY IF EXISTS "Acesso Global Clientes" ON public."clientes";
CREATE POLICY "Acesso Global Clientes" ON public."clientes"
  AS PERMISSIVE
  FOR ALL
  TO public
  USING ((auth.role() = 'authenticated'::text));

DROP POLICY IF EXISTS "public_select_clientes" ON public."clientes";
CREATE POLICY "public_select_clientes" ON public."clientes"
  AS PERMISSIVE
  FOR SELECT
  TO public
  USING (true);

DROP POLICY IF EXISTS "Acesso Global Contas Pagar Fornecedor" ON public."contas_pagar_fornecedor";
CREATE POLICY "Acesso Global Contas Pagar Fornecedor" ON public."contas_pagar_fornecedor"
  AS PERMISSIVE
  FOR ALL
  TO authenticated
  USING ((auth.role() = 'authenticated'::text))
  WITH CHECK ((auth.role() = 'authenticated'::text));

DROP POLICY IF EXISTS "Qualquer autenticado insere no cronograma" ON public."cronograma_eventos";
CREATE POLICY "Qualquer autenticado insere no cronograma" ON public."cronograma_eventos"
  AS PERMISSIVE
  FOR INSERT
  TO public
  WITH CHECK ((auth.role() = 'authenticated'::text));

DROP POLICY IF EXISTS "Qualquer autenticado vê o cronograma" ON public."cronograma_eventos";
CREATE POLICY "Qualquer autenticado vê o cronograma" ON public."cronograma_eventos"
  AS PERMISSIVE
  FOR SELECT
  TO public
  USING ((auth.role() = 'authenticated'::text));

DROP POLICY IF EXISTS "Usuários deletam seus próprios eventos" ON public."cronograma_eventos";
CREATE POLICY "Usuários deletam seus próprios eventos" ON public."cronograma_eventos"
  AS PERMISSIVE
  FOR DELETE
  TO public
  USING ((auth.uid() = user_id));

DROP POLICY IF EXISTS "Usuários editam seus próprios eventos" ON public."cronograma_eventos";
CREATE POLICY "Usuários editam seus próprios eventos" ON public."cronograma_eventos"
  AS PERMISSIVE
  FOR UPDATE
  TO public
  USING ((auth.uid() = user_id));

DROP POLICY IF EXISTS "Apenas o autor pode apagar" ON public."diario_obras";
CREATE POLICY "Apenas o autor pode apagar" ON public."diario_obras"
  AS PERMISSIVE
  FOR DELETE
  TO public
  USING ((auth.uid() = user_id));

DROP POLICY IF EXISTS "Apenas o autor pode atualizar" ON public."diario_obras";
CREATE POLICY "Apenas o autor pode atualizar" ON public."diario_obras"
  AS PERMISSIVE
  FOR UPDATE
  TO public
  USING ((auth.uid() = user_id))
  WITH CHECK ((auth.uid() = user_id));

DROP POLICY IF EXISTS "Todos podem ver o diário" ON public."diario_obras";
CREATE POLICY "Todos podem ver o diário" ON public."diario_obras"
  AS PERMISSIVE
  FOR SELECT
  TO public
  USING ((auth.role() = 'authenticated'::text));

DROP POLICY IF EXISTS "Utilizadores inserem os seus registos" ON public."diario_obras";
CREATE POLICY "Utilizadores inserem os seus registos" ON public."diario_obras"
  AS PERMISSIVE
  FOR INSERT
  TO public
  WITH CHECK (((auth.role() = 'authenticated'::text) AND (auth.uid() = user_id)));

DROP POLICY IF EXISTS "Acesso Restrito Entradas" ON public."entradas";
CREATE POLICY "Acesso Restrito Entradas" ON public."entradas"
  AS PERMISSIVE
  FOR ALL
  TO public
  USING (((auth_user_tipo() = 'gestor_master'::text) OR ((auth_user_tipo() = 'diretoria'::text) AND ((escritorio = auth_user_escritorio()) OR (escritorio = 'Montezuma'::text))) OR ((auth_user_tipo() = 'secretaria'::text) AND (escritorio = 'Montezuma'::text))));

DROP POLICY IF EXISTS "Acesso Global Fornecedores" ON public."fornecedores";
CREATE POLICY "Acesso Global Fornecedores" ON public."fornecedores"
  AS PERMISSIVE
  FOR ALL
  TO public
  USING ((auth.role() = 'authenticated'::text));

DROP POLICY IF EXISTS "Permitir leitura publica lote itens" ON public."obra_lote_itens";
CREATE POLICY "Permitir leitura publica lote itens" ON public."obra_lote_itens"
  AS PERMISSIVE
  FOR SELECT
  TO public
  USING (true);

DROP POLICY IF EXISTS "obra_lote_itens_select" ON public."obra_lote_itens";
CREATE POLICY "obra_lote_itens_select" ON public."obra_lote_itens"
  AS PERMISSIVE
  FOR SELECT
  TO authenticated
  USING ((EXISTS ( SELECT 1
   FROM usuarios u
  WHERE ((u.id = auth.uid()) AND (u.tipo = ANY (ARRAY['diretoria'::text, 'gestor_master'::text, 'suporte_ti'::text, 'secretaria'::text, 'encarregado'::text]))))));

DROP POLICY IF EXISTS "obra_lote_itens_write" ON public."obra_lote_itens";
CREATE POLICY "obra_lote_itens_write" ON public."obra_lote_itens"
  AS PERMISSIVE
  FOR ALL
  TO authenticated
  USING ((EXISTS ( SELECT 1
   FROM usuarios u
  WHERE ((u.id = auth.uid()) AND (u.tipo = ANY (ARRAY['diretoria'::text, 'gestor_master'::text, 'suporte_ti'::text, 'encarregado'::text]))))))
  WITH CHECK ((EXISTS ( SELECT 1
   FROM usuarios u
  WHERE ((u.id = auth.uid()) AND (u.tipo = ANY (ARRAY['diretoria'::text, 'gestor_master'::text, 'suporte_ti'::text, 'encarregado'::text]))))));

DROP POLICY IF EXISTS "Permitir leitura publica lotes pagamento" ON public."obra_lotes_pagamento";
CREATE POLICY "Permitir leitura publica lotes pagamento" ON public."obra_lotes_pagamento"
  AS PERMISSIVE
  FOR SELECT
  TO public
  USING (true);

DROP POLICY IF EXISTS "obra_lotes_pagamento_select" ON public."obra_lotes_pagamento";
CREATE POLICY "obra_lotes_pagamento_select" ON public."obra_lotes_pagamento"
  AS PERMISSIVE
  FOR SELECT
  TO authenticated
  USING ((EXISTS ( SELECT 1
   FROM usuarios u
  WHERE ((u.id = auth.uid()) AND (u.tipo = ANY (ARRAY['diretoria'::text, 'gestor_master'::text, 'suporte_ti'::text, 'secretaria'::text, 'encarregado'::text]))))));

DROP POLICY IF EXISTS "obra_lotes_pagamento_write" ON public."obra_lotes_pagamento";
CREATE POLICY "obra_lotes_pagamento_write" ON public."obra_lotes_pagamento"
  AS PERMISSIVE
  FOR ALL
  TO authenticated
  USING ((EXISTS ( SELECT 1
   FROM usuarios u
  WHERE ((u.id = auth.uid()) AND (u.tipo = ANY (ARRAY['diretoria'::text, 'gestor_master'::text, 'suporte_ti'::text, 'encarregado'::text]))))))
  WITH CHECK ((EXISTS ( SELECT 1
   FROM usuarios u
  WHERE ((u.id = auth.uid()) AND (u.tipo = ANY (ARRAY['diretoria'::text, 'gestor_master'::text, 'suporte_ti'::text, 'encarregado'::text]))))));

DROP POLICY IF EXISTS "obra_movimentacoes_delete" ON public."obra_movimentacoes";
CREATE POLICY "obra_movimentacoes_delete" ON public."obra_movimentacoes"
  AS PERMISSIVE
  FOR DELETE
  TO authenticated
  USING ((EXISTS ( SELECT 1
   FROM usuarios u
  WHERE ((u.id = auth.uid()) AND (u.tipo = ANY (ARRAY['diretoria'::text, 'gestor_master'::text, 'suporte_ti'::text]))))));

DROP POLICY IF EXISTS "obra_movimentacoes_insert" ON public."obra_movimentacoes";
CREATE POLICY "obra_movimentacoes_insert" ON public."obra_movimentacoes"
  AS PERMISSIVE
  FOR INSERT
  TO authenticated
  WITH CHECK ((EXISTS ( SELECT 1
   FROM usuarios u
  WHERE ((u.id = auth.uid()) AND (u.tipo = ANY (ARRAY['diretoria'::text, 'gestor_master'::text, 'suporte_ti'::text]))))));

DROP POLICY IF EXISTS "obra_movimentacoes_select" ON public."obra_movimentacoes";
CREATE POLICY "obra_movimentacoes_select" ON public."obra_movimentacoes"
  AS PERMISSIVE
  FOR SELECT
  TO authenticated
  USING ((EXISTS ( SELECT 1
   FROM usuarios u
  WHERE ((u.id = auth.uid()) AND (u.tipo = ANY (ARRAY['diretoria'::text, 'gestor_master'::text, 'suporte_ti'::text, 'secretaria'::text, 'encarregado'::text]))))));

DROP POLICY IF EXISTS "obra_movimentacoes_update" ON public."obra_movimentacoes";
CREATE POLICY "obra_movimentacoes_update" ON public."obra_movimentacoes"
  AS PERMISSIVE
  FOR UPDATE
  TO authenticated
  USING ((EXISTS ( SELECT 1
   FROM usuarios u
  WHERE ((u.id = auth.uid()) AND (u.tipo = ANY (ARRAY['diretoria'::text, 'gestor_master'::text, 'suporte_ti'::text]))))))
  WITH CHECK ((EXISTS ( SELECT 1
   FROM usuarios u
  WHERE ((u.id = auth.uid()) AND (u.tipo = ANY (ARRAY['diretoria'::text, 'gestor_master'::text, 'suporte_ti'::text]))))));

DROP POLICY IF EXISTS "obra_pedido_grupos_compra_all" ON public."obra_pedido_grupos_compra";
CREATE POLICY "obra_pedido_grupos_compra_all" ON public."obra_pedido_grupos_compra"
  AS PERMISSIVE
  FOR ALL
  TO public
  USING (true)
  WITH CHECK (true);

DROP POLICY IF EXISTS "obra_pedido_itens_all" ON public."obra_pedido_itens";
CREATE POLICY "obra_pedido_itens_all" ON public."obra_pedido_itens"
  AS PERMISSIVE
  FOR ALL
  TO public
  USING (true)
  WITH CHECK (true);

DROP POLICY IF EXISTS "obra_pedidos_all" ON public."obra_pedidos";
CREATE POLICY "obra_pedidos_all" ON public."obra_pedidos"
  AS PERMISSIVE
  FOR ALL
  TO public
  USING (true)
  WITH CHECK (true);

DROP POLICY IF EXISTS "Acesso Global Obras" ON public."obras";
CREATE POLICY "Acesso Global Obras" ON public."obras"
  AS PERMISSIVE
  FOR ALL
  TO public
  USING ((auth.role() = 'authenticated'::text));

DROP POLICY IF EXISTS "Permitir leitura publica obras" ON public."obras";
CREATE POLICY "Permitir leitura publica obras" ON public."obras"
  AS PERMISSIVE
  FOR SELECT
  TO anon
  USING (true);

DROP POLICY IF EXISTS "Acesso Restrito Orcamentos" ON public."orcamentos";
CREATE POLICY "Acesso Restrito Orcamentos" ON public."orcamentos"
  AS PERMISSIVE
  FOR ALL
  TO public
  USING (((auth_user_tipo() = 'gestor_master'::text) OR ((auth_user_tipo() = 'diretoria'::text) AND ((escritorio = auth_user_escritorio()) OR (escritorio = 'Montezuma'::text))) OR ((auth_user_tipo() = 'secretaria'::text) AND (escritorio = 'Montezuma'::text))));

DROP POLICY IF EXISTS "ordens_servico_delete" ON public."ordens_servico";
CREATE POLICY "ordens_servico_delete" ON public."ordens_servico"
  AS PERMISSIVE
  FOR DELETE
  TO authenticated
  USING (usuario_pode_excluir_ordem_servico(ordens_servico.*));

DROP POLICY IF EXISTS "ordens_servico_insert" ON public."ordens_servico";
CREATE POLICY "ordens_servico_insert" ON public."ordens_servico"
  AS PERMISSIVE
  FOR INSERT
  TO authenticated
  WITH CHECK (((criador_id = auth.uid()) AND (EXISTS ( SELECT 1
   FROM usuarios u
  WHERE ((u.id = auth.uid()) AND ((u.tipo = 'gestor_master'::text) OR (u.subclasses @> '["emissor_os_gestor"]'::jsonb) OR (u.subclasses @> '["emissor_os_encarregado"]'::jsonb)))))));

DROP POLICY IF EXISTS "ordens_servico_select" ON public."ordens_servico";
CREATE POLICY "ordens_servico_select" ON public."ordens_servico"
  AS PERMISSIVE
  FOR SELECT
  TO authenticated
  USING (usuario_pode_ver_ordem_servico(ordens_servico.*));

DROP POLICY IF EXISTS "ordens_servico_update" ON public."ordens_servico";
CREATE POLICY "ordens_servico_update" ON public."ordens_servico"
  AS PERMISSIVE
  FOR UPDATE
  TO authenticated
  USING (usuario_pode_ver_ordem_servico(ordens_servico.*))
  WITH CHECK (usuario_pode_ver_ordem_servico(ordens_servico.*));

DROP POLICY IF EXISTS "Acesso Global Prestadores" ON public."prestadores";
CREATE POLICY "Acesso Global Prestadores" ON public."prestadores"
  AS PERMISSIVE
  FOR ALL
  TO public
  USING ((auth.role() = 'authenticated'::text));

DROP POLICY IF EXISTS "Acesso Global Prestadores Classes" ON public."prestadores_classes";
CREATE POLICY "Acesso Global Prestadores Classes" ON public."prestadores_classes"
  AS PERMISSIVE
  FOR ALL
  TO public
  USING ((auth.role() = 'authenticated'::text));

DROP POLICY IF EXISTS "projecoes_authenticated_all" ON public."projecoes";
CREATE POLICY "projecoes_authenticated_all" ON public."projecoes"
  AS PERMISSIVE
  FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

DROP POLICY IF EXISTS "Acesso Global Rel Ext" ON public."relatorio_extrato";
CREATE POLICY "Acesso Global Rel Ext" ON public."relatorio_extrato"
  AS PERMISSIVE
  FOR ALL
  TO public
  USING ((auth.role() = 'authenticated'::text));

DROP POLICY IF EXISTS "Permitir leitura publica extrato" ON public."relatorio_extrato";
CREATE POLICY "Permitir leitura publica extrato" ON public."relatorio_extrato"
  AS PERMISSIVE
  FOR SELECT
  TO anon
  USING (true);

DROP POLICY IF EXISTS "relatorio_locacoes_delete" ON public."relatorio_locacoes";
CREATE POLICY "relatorio_locacoes_delete" ON public."relatorio_locacoes"
  AS PERMISSIVE
  FOR DELETE
  TO authenticated
  USING (true);

DROP POLICY IF EXISTS "relatorio_locacoes_insert" ON public."relatorio_locacoes";
CREATE POLICY "relatorio_locacoes_insert" ON public."relatorio_locacoes"
  AS PERMISSIVE
  FOR INSERT
  TO authenticated
  WITH CHECK (true);

DROP POLICY IF EXISTS "relatorio_locacoes_select" ON public."relatorio_locacoes";
CREATE POLICY "relatorio_locacoes_select" ON public."relatorio_locacoes"
  AS PERMISSIVE
  FOR SELECT
  TO authenticated
  USING (true);

DROP POLICY IF EXISTS "relatorio_locacoes_update" ON public."relatorio_locacoes";
CREATE POLICY "relatorio_locacoes_update" ON public."relatorio_locacoes"
  AS PERMISSIVE
  FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

DROP POLICY IF EXISTS "Acesso Global Rel MDO" ON public."relatorio_mao_de_obra";
CREATE POLICY "Acesso Global Rel MDO" ON public."relatorio_mao_de_obra"
  AS PERMISSIVE
  FOR ALL
  TO public
  USING ((auth.role() = 'authenticated'::text));

DROP POLICY IF EXISTS "Permitir leitura publica mdo" ON public."relatorio_mao_de_obra";
CREATE POLICY "Permitir leitura publica mdo" ON public."relatorio_mao_de_obra"
  AS PERMISSIVE
  FOR SELECT
  TO anon
  USING (true);

DROP POLICY IF EXISTS "Acesso Global Rel Mat" ON public."relatorio_materiais";
CREATE POLICY "Acesso Global Rel Mat" ON public."relatorio_materiais"
  AS PERMISSIVE
  FOR ALL
  TO public
  USING ((auth.role() = 'authenticated'::text));

DROP POLICY IF EXISTS "Permitir leitura publica materiais" ON public."relatorio_materiais";
CREATE POLICY "Permitir leitura publica materiais" ON public."relatorio_materiais"
  AS PERMISSIVE
  FOR SELECT
  TO anon
  USING (true);

DROP POLICY IF EXISTS "relatorios_diretoria_delete" ON public."relatorios_diretoria";
CREATE POLICY "relatorios_diretoria_delete" ON public."relatorios_diretoria"
  AS PERMISSIVE
  FOR DELETE
  TO authenticated
  USING ((EXISTS ( SELECT 1
   FROM usuarios u
  WHERE ((u.id = auth.uid()) AND (u.tipo = ANY (ARRAY['diretoria'::text, 'gestor_master'::text]))))));

DROP POLICY IF EXISTS "relatorios_diretoria_insert" ON public."relatorios_diretoria";
CREATE POLICY "relatorios_diretoria_insert" ON public."relatorios_diretoria"
  AS PERMISSIVE
  FOR INSERT
  TO authenticated
  WITH CHECK ((EXISTS ( SELECT 1
   FROM usuarios u
  WHERE ((u.id = auth.uid()) AND (u.tipo = ANY (ARRAY['diretoria'::text, 'gestor_master'::text]))))));

DROP POLICY IF EXISTS "relatorios_diretoria_select" ON public."relatorios_diretoria";
CREATE POLICY "relatorios_diretoria_select" ON public."relatorios_diretoria"
  AS PERMISSIVE
  FOR SELECT
  TO authenticated
  USING ((EXISTS ( SELECT 1
   FROM usuarios u
  WHERE ((u.id = auth.uid()) AND (u.tipo = ANY (ARRAY['diretoria'::text, 'gestor_master'::text]))))));

DROP POLICY IF EXISTS "relatorios_diretoria_update" ON public."relatorios_diretoria";
CREATE POLICY "relatorios_diretoria_update" ON public."relatorios_diretoria"
  AS PERMISSIVE
  FOR UPDATE
  TO authenticated
  USING ((EXISTS ( SELECT 1
   FROM usuarios u
  WHERE ((u.id = auth.uid()) AND (u.tipo = ANY (ARRAY['diretoria'::text, 'gestor_master'::text]))))))
  WITH CHECK ((EXISTS ( SELECT 1
   FROM usuarios u
  WHERE ((u.id = auth.uid()) AND (u.tipo = ANY (ARRAY['diretoria'::text, 'gestor_master'::text]))))));

DROP POLICY IF EXISTS "reservas_sala_delete" ON public."reservas_sala";
CREATE POLICY "reservas_sala_delete" ON public."reservas_sala"
  AS PERMISSIVE
  FOR DELETE
  TO authenticated
  USING ((EXISTS ( SELECT 1
   FROM usuarios u
  WHERE ((u.id = auth.uid()) AND (u.tipo = ANY (ARRAY['diretoria'::text, 'gestor_master'::text]))))));

DROP POLICY IF EXISTS "reservas_sala_insert" ON public."reservas_sala";
CREATE POLICY "reservas_sala_insert" ON public."reservas_sala"
  AS PERMISSIVE
  FOR INSERT
  TO authenticated
  WITH CHECK ((EXISTS ( SELECT 1
   FROM usuarios u
  WHERE ((u.id = auth.uid()) AND (u.tipo = ANY (ARRAY['diretoria'::text, 'gestor_master'::text]))))));

DROP POLICY IF EXISTS "reservas_sala_select" ON public."reservas_sala";
CREATE POLICY "reservas_sala_select" ON public."reservas_sala"
  AS PERMISSIVE
  FOR SELECT
  TO authenticated
  USING ((EXISTS ( SELECT 1
   FROM usuarios u
  WHERE ((u.id = auth.uid()) AND (u.tipo = ANY (ARRAY['diretoria'::text, 'gestor_master'::text]))))));

DROP POLICY IF EXISTS "reservas_sala_update" ON public."reservas_sala";
CREATE POLICY "reservas_sala_update" ON public."reservas_sala"
  AS PERMISSIVE
  FOR UPDATE
  TO authenticated
  USING ((EXISTS ( SELECT 1
   FROM usuarios u
  WHERE ((u.id = auth.uid()) AND (u.tipo = ANY (ARRAY['diretoria'::text, 'gestor_master'::text]))))))
  WITH CHECK ((EXISTS ( SELECT 1
   FROM usuarios u
  WHERE ((u.id = auth.uid()) AND (u.tipo = ANY (ARRAY['diretoria'::text, 'gestor_master'::text]))))));

DROP POLICY IF EXISTS "Acesso Restrito Saidas" ON public."saida";
CREATE POLICY "Acesso Restrito Saidas" ON public."saida"
  AS PERMISSIVE
  FOR ALL
  TO public
  USING (((auth_user_tipo() = 'gestor_master'::text) OR ((auth_user_tipo() = 'diretoria'::text) AND ((escritorio = auth_user_escritorio()) OR (escritorio = 'Montezuma'::text))) OR ((auth_user_tipo() = 'secretaria'::text) AND (escritorio = 'Montezuma'::text))));

DROP POLICY IF EXISTS "Acesso Tarefa Responsaveis ALL" ON public."tarefa_responsaveis";
CREATE POLICY "Acesso Tarefa Responsaveis ALL" ON public."tarefa_responsaveis"
  AS PERMISSIVE
  FOR INSERT
  TO public
  WITH CHECK ((auth_user_tipo() = ANY (ARRAY['gestor_master'::text, 'diretoria'::text])));

DROP POLICY IF EXISTS "Acesso Tarefa Responsaveis DEL" ON public."tarefa_responsaveis";
CREATE POLICY "Acesso Tarefa Responsaveis DEL" ON public."tarefa_responsaveis"
  AS PERMISSIVE
  FOR DELETE
  TO public
  USING ((auth_user_tipo() = ANY (ARRAY['gestor_master'::text, 'diretoria'::text])));

DROP POLICY IF EXISTS "Acesso Tarefa Responsaveis SELECT" ON public."tarefa_responsaveis";
CREATE POLICY "Acesso Tarefa Responsaveis SELECT" ON public."tarefa_responsaveis"
  AS PERMISSIVE
  FOR SELECT
  TO public
  USING ((auth.role() = 'authenticated'::text));

DROP POLICY IF EXISTS "Permitir leitura geral de tarefa_responsaveis" ON public."tarefa_responsaveis";
CREATE POLICY "Permitir leitura geral de tarefa_responsaveis" ON public."tarefa_responsaveis"
  AS PERMISSIVE
  FOR SELECT
  TO public
  USING ((auth.role() = 'authenticated'::text));

DROP POLICY IF EXISTS "Acesso Tarefas" ON public."tarefas";
CREATE POLICY "Acesso Tarefas" ON public."tarefas"
  AS PERMISSIVE
  FOR ALL
  TO public
  USING (((auth_user_tipo() = ANY (ARRAY['gestor_master'::text, 'diretoria'::text])) OR (EXISTS ( SELECT 1
   FROM tarefa_responsaveis tr
  WHERE ((tr.tarefa_id = tarefas.id) AND (tr.usuario_id = auth.uid()))))));

DROP POLICY IF EXISTS "Secretaria vê tudo, restantes vêem o seu" ON public."tarefas";
CREATE POLICY "Secretaria vê tudo, restantes vêem o seu" ON public."tarefas"
  AS PERMISSIVE
  FOR SELECT
  TO public
  USING (((auth.uid() IN ( SELECT usuarios.id
   FROM usuarios
  WHERE (usuarios.tipo = 'secretaria'::text))) OR (escritorio_id = auth.uid())));

DROP POLICY IF EXISTS "Permitir leitura de dados basicos de usuarios" ON public."usuarios";
CREATE POLICY "Permitir leitura de dados basicos de usuarios" ON public."usuarios"
  AS PERMISSIVE
  FOR SELECT
  TO public
  USING ((auth.role() = 'authenticated'::text));

DROP POLICY IF EXISTS "Visibilidade Usuarios" ON public."usuarios";
CREATE POLICY "Visibilidade Usuarios" ON public."usuarios"
  AS PERMISSIVE
  FOR SELECT
  TO public
  USING (((auth_user_tipo() = 'gestor_master'::text) OR ((auth_user_tipo() = 'diretoria'::text) AND (escritorio = auth_user_escritorio())) OR (id = auth.uid())));

DROP POLICY IF EXISTS "usuarios_select_authenticated" ON public."usuarios";
CREATE POLICY "usuarios_select_authenticated" ON public."usuarios"
  AS PERMISSIVE
  FOR SELECT
  TO authenticated
  USING (true);

DROP POLICY IF EXISTS "usuarios_update_perfil" ON public."usuarios";
CREATE POLICY "usuarios_update_perfil" ON public."usuarios"
  AS PERMISSIVE
  FOR UPDATE
  TO authenticated
  USING (usuario_pode_editar_usuario(usuarios.*))
  WITH CHECK (usuario_pode_editar_usuario(usuarios.*));

DROP TRIGGER IF EXISTS trg_agenda_updated_at ON public.agenda;
CREATE TRIGGER trg_agenda_updated_at
  BEFORE UPDATE ON public.agenda
  FOR EACH ROW
  EXECUTE FUNCTION agenda_set_updated_at();

DROP TRIGGER IF EXISTS trg_cliente_historico_set_updated_at ON public.cliente_historico;
CREATE TRIGGER trg_cliente_historico_set_updated_at
  BEFORE UPDATE ON public.cliente_historico
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_check_extrato_not_in_open_lote ON public.obra_lote_itens;
CREATE TRIGGER trg_check_extrato_not_in_open_lote
  BEFORE INSERT OR UPDATE ON public.obra_lote_itens
  FOR EACH ROW
  EXECUTE FUNCTION check_extrato_not_in_open_lote();

DROP TRIGGER IF EXISTS trg_projecoes_updated_at ON public.projecoes;
CREATE TRIGGER trg_projecoes_updated_at
  BEFORE UPDATE ON public.projecoes
  FOR EACH ROW
  EXECUTE FUNCTION set_projecoes_updated_at();

DROP TRIGGER IF EXISTS trg_reservas_sala_no_overlap ON public.reservas_sala;
CREATE TRIGGER trg_reservas_sala_no_overlap
  BEFORE INSERT OR UPDATE ON public.reservas_sala
  FOR EACH ROW
  EXECUTE FUNCTION check_reservas_sala_no_overlap();

DROP TRIGGER IF EXISTS trg_reservas_sala_updated_at ON public.reservas_sala;
CREATE TRIGGER trg_reservas_sala_updated_at
  BEFORE UPDATE ON public.reservas_sala
  FOR EACH ROW
  EXECUTE FUNCTION set_reservas_sala_updated_at();

INSERT INTO storage.buckets (id, name, public)
VALUES ('assinaturas_usuarios', 'assinaturas_usuarios', true)
ON CONFLICT (id) DO NOTHING;
INSERT INTO storage.buckets (id, name, public)
VALUES ('fotos_clientes', 'fotos_clientes', true)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "Permitir Upload Público ucgxzd_0" ON storage.objects;
CREATE POLICY "Permitir Upload Público ucgxzd_0" ON storage.objects
  FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "Permitir Upload Público ucgxzd_1" ON storage.objects;
CREATE POLICY "Permitir Upload Público ucgxzd_1" ON storage.objects
  FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS assinaturas_usuarios_select ON storage.objects;
CREATE POLICY assinaturas_usuarios_select ON storage.objects
  FOR SELECT TO public USING (bucket_id = 'assinaturas_usuarios');
DROP POLICY IF EXISTS assinaturas_usuarios_insert ON storage.objects;
CREATE POLICY assinaturas_usuarios_insert ON storage.objects
  FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'assinaturas_usuarios' AND ((storage.foldername(name))[1] = (auth.uid())::text OR public.usuario_eh_gestor_sistema()));
DROP POLICY IF EXISTS assinaturas_usuarios_update ON storage.objects;
CREATE POLICY assinaturas_usuarios_update ON storage.objects
  FOR UPDATE TO authenticated
  USING (bucket_id = 'assinaturas_usuarios' AND ((storage.foldername(name))[1] = (auth.uid())::text OR public.usuario_eh_gestor_sistema()));
DROP POLICY IF EXISTS assinaturas_usuarios_delete ON storage.objects;
CREATE POLICY assinaturas_usuarios_delete ON storage.objects
  FOR DELETE TO authenticated
  USING (bucket_id = 'assinaturas_usuarios' AND ((storage.foldername(name))[1] = (auth.uid())::text OR public.usuario_eh_gestor_sistema()));

GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA private TO postgres, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO anon, authenticated, service_role;

