-- Contas a pagar Montezuma → Fornecedor (separado do extrato Cliente → Montezuma)

CREATE TABLE IF NOT EXISTS public.contas_pagar_fornecedor (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  material_id bigint NOT NULL UNIQUE
    REFERENCES public.relatorio_materiais(id) ON DELETE CASCADE,
  obra_id bigint NOT NULL REFERENCES public.obras(id),
  fornecedor_id uuid NOT NULL REFERENCES public.fornecedores(id),
  descricao text NOT NULL,
  valor double precision NOT NULL DEFAULT 0,
  data_vencimento date,
  status_pagamento text NOT NULL DEFAULT 'Aguardando pagamento'
    CHECK (status_pagamento IN ('Aguardando pagamento', 'Pago')),
  data_pagamento timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_contas_pagar_fornecedor_fornecedor
  ON public.contas_pagar_fornecedor (fornecedor_id);

CREATE INDEX IF NOT EXISTS idx_contas_pagar_fornecedor_status
  ON public.contas_pagar_fornecedor (status_pagamento);

CREATE INDEX IF NOT EXISTS idx_contas_pagar_fornecedor_vencimento
  ON public.contas_pagar_fornecedor (data_vencimento);

CREATE INDEX IF NOT EXISTS idx_contas_pagar_fornecedor_obra
  ON public.contas_pagar_fornecedor (obra_id);

-- Backfill zerado: ignora status_financeiro legado; tudo Aguardando pagamento
INSERT INTO public.contas_pagar_fornecedor (
  material_id,
  obra_id,
  fornecedor_id,
  descricao,
  valor,
  data_vencimento,
  status_pagamento
)
SELECT
  m.id,
  m.obra_id,
  m.fornecedor_id,
  COALESCE(NULLIF(TRIM(m.material), ''), 'Material'),
  COALESCE(m.valor, 0),
  m.data_vencimento,
  'Aguardando pagamento'
FROM public.relatorio_materiais m
WHERE m.fornecedor_id IS NOT NULL
  AND m.obra_id IS NOT NULL
ON CONFLICT (material_id) DO NOTHING;

ALTER TABLE public.contas_pagar_fornecedor ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Acesso Global Contas Pagar Fornecedor"
  ON public.contas_pagar_fornecedor
  FOR ALL
  TO authenticated
  USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');
