-- Relatório de locações de equipamentos por obra
CREATE TABLE IF NOT EXISTS public.relatorio_locacoes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  obra_id bigint NOT NULL REFERENCES public.obras (id) ON DELETE CASCADE,
  equipamento text NOT NULL,
  quantidade numeric(12, 2) NOT NULL CHECK (quantidade > 0),
  tipo_periodo text NOT NULL CHECK (
    tipo_periodo IN ('Diário', 'Semanal', 'Mensal', 'Anual')
  ),
  periodo integer NOT NULL CHECK (periodo > 0),
  solicitante text NOT NULL,
  data_solicitacao date NOT NULL DEFAULT (CURRENT_DATE),
  data_vencimento date,
  valor numeric(14, 2) NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'Solicitado',
  status_financeiro text NOT NULL DEFAULT 'Aguardando pagamento',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS relatorio_locacoes_obra_id_idx
  ON public.relatorio_locacoes (obra_id);

CREATE INDEX IF NOT EXISTS relatorio_locacoes_created_at_idx
  ON public.relatorio_locacoes (created_at DESC);

COMMENT ON TABLE public.relatorio_locacoes IS
  'Locações de equipamentos/ferramentas vinculadas ao relatório da obra';

ALTER TABLE public.relatorio_locacoes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS relatorio_locacoes_select ON public.relatorio_locacoes;
DROP POLICY IF EXISTS relatorio_locacoes_insert ON public.relatorio_locacoes;
DROP POLICY IF EXISTS relatorio_locacoes_update ON public.relatorio_locacoes;
DROP POLICY IF EXISTS relatorio_locacoes_delete ON public.relatorio_locacoes;

CREATE POLICY relatorio_locacoes_select ON public.relatorio_locacoes
  FOR SELECT TO authenticated USING (true);

CREATE POLICY relatorio_locacoes_insert ON public.relatorio_locacoes
  FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY relatorio_locacoes_update ON public.relatorio_locacoes
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY relatorio_locacoes_delete ON public.relatorio_locacoes
  FOR DELETE TO authenticated USING (true);
